# Generated by Django 5.2 on 2025-05-12 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=10, unique=True)),
                ('message_body', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('is_phishing', models.BooleanField(default=False)),
                ('reasons', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Phishing detection',
                'verbose_name_plural': 'Phishing detections',
            },
        ),
    ]
