# Generated by Django 5.2 on 2025-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingDetector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingdetection',
            name='reasons',
            field=models.CharField(max_length=500),
        ),
    ]
