# Generated by Django 5.2 on 2025-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingDetector', '0002_alter_phishingdetection_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingdetection',
            name='message_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phishingdetection',
            name='message_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phishingdetection',
            name='reasons',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phishingdetection',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phishingdetection',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
