# Generated by Django 5.2 on 2025-04-27 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_dashboard', models.BooleanField(default=False)),
                ('view_message', models.BooleanField(default=False)),
                ('view_chat', models.BooleanField(default=False)),
                ('view_setting', models.BooleanField(default=False)),
                ('view_logs', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authorization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorization',
                'verbose_name_plural': 'Authorizations',
            },
        ),
    ]
